Initialize directory for production installation
Nix-Security-WG/nix-security-tracker pull request #412
Opened 2024-12-04 00:36 UTC by Erethon

This PR initializes the directory for the production installation of the security tracker. It currently:
- Creates a new directory and a simple README for the infra
- Initializes a Terraform/OpenTofu setup for our Hetzner Cloud VMs
  - I've got two minor TODOs here that I want to discuss during a sync
  
 I'm leaving this as draft untill we discuss a couple of things. After that's done we can review it and merge it, or leave it open to add the NixOS related bits of configuration as well.
 
Closes #370

2024-12-05 11:16 UTC, fricklerhandwerk requested changes
- `infra/shell.nix` is missing
- please add URLs to where to manage the Hetzner deployment, and where to find out who has access

2024-12-05 11:16 UTC, fricklerhandwerk commented on infra/README.md
> +[instructions on the NixOS wiki](https://wiki.nixos.org/wiki/Install_NixOS_on_Hetzner_Cloud#Traditional_ISO_installation).
```suggestion
[provisioning NixOS via SSH tutorial](https://nix.dev/tutorials/nixos/provisioning-remote-machines).
```

2024-12-05 21:41 UTC, fricklerhandwerk approved these changes

2024-12-05 22:25 UTC, merged

2024-12-10 23:06 UTC, Erethon commented
I just noticed the changes pushed in this PR. @fricklerhandwerk is there a reason to move the terraform files outside of the terraform directory?

Moreover, since the move, `nix-shell` doesn't work because we're pointing to the wrong npins (two directories up instead of one).  https://github.com/erethon/nix-security-tracker/commit/50da9709310d8a5002a5e619bf1ad6ecc2a27512 fixes this, but I'm not a fan of using the versions of this specific npins file. I wonder what's the proper way to specify a particular branch (say nixos-24.11) just for this shell.

2024-12-10 23:48 UTC, fricklerhandwerk commented
Ah right, I was a bit fast, sorry. You can just initialise a separate `npins` in that subdirectory and import from there. One directory for one file seemed a bit excessive, I took the liberty excercise my authority as product owner to keep code readability in check for myself. :) If that was naive of me, feel free to change it back with a line of rationale.