set up groups and permissions
Nix-Security-WG/nix-security-tracker pull request #67
Opened 2023-12-07 00:34 UTC by fricklerhandwerk

2023-12-07 11:37 UTC, RaitoBezarius commented on src/website/webview/apps.py
> +    secteam, created = Group.objects.get_or_create(name="Security team")
Why do we make dynamic groups? This feel overly complicated? All our groups are statically known: superadmins, security team, committers, maintainers, viewers. Do you want to bring more groups than those?

2023-12-07 11:38 UTC, RaitoBezarius requested changes
I am quite meh about the packaging changes for Python (I spent some time on fixing the mess that was happening out there.) and I do not understand the need of the extra dependency.

2023-12-07 11:40 UTC, RaitoBezarius commented
Ah I think I fucked up my commits and the missing commit for you is here: https://github.com/Nix-Security-WG/nix-security-tracker/pull/59/commits/67dd36db418ca486afc66afa235d9f45d0b67f2f.

2023-12-07 13:21 UTC, fricklerhandwerk commented on pkgs/python/django-pgpubsub/default.nix
> +{ lib, buildPythonPackage, fetchFromGitHub, python3 }:
Right. Makes a few things simpler. I just figured that the way we build `callPackage` is weird and we should stick to the regular Nixpkgs structure, but it's probably overthinking it.

2023-12-07 13:32 UTC, RaitoBezarius commented
The important part for permissions will be the REST API we will build, we have https://www.django-rest-framework.org/api-guide/permissions/ for that.

2023-12-07 13:33 UTC, RaitoBezarius commented
For views, we already have the built-in system in https://docs.djangoproject.com/en/5.0/topics/auth/default/#permissions-and-authorization.

2024-08-15 13:31 UTC, alejandrosame commented
Groups and permissions scaffold was implemented with #165 (already merged).

2024-08-15 13:31 UTC, closed without merging